# Housing Rental Analysis for San Francisco

In this challenge, your job is to use your data visualisation skills, including aggregation, interactive visualisations, and geospatial analysis, to find properties in the San Francisco market that are viable investment opportunities.

### Instructions

Use the `san_francisco_housing.ipynb` notebook to visualise and analyse the real-estate data.

Note that this assignment requires you to create a visualisation by using hvPlot and GeoViews. Additionally, you need to read the `sfo_neighborhoods_census_data.csv` file from the `Resources` folder into the notebook and create the DataFrame that you’ll use in the analysis.

The main task in this Challenge is to visualise and analyse the real-estate data in your Jupyter notebook. Use the `san_francisco_housing.ipynb` notebook to complete the following tasks:

* Calculate and plot the housing units per year.

* Calculate and plot the average prices per square foot.

* Compare the average prices by neighbourhood.

* Build an interactive neighbourhood map.

* Compose your data story.

#### Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualisation.

4. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting bar chart.](Images/6-4-zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analysing?

#### Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?

#### Compare the Average Sale Prices by Neighbourhood

For this part of the assignment, use interactive visualisations and widgets to explore the average sale price per square foot by neighbourhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighbourhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighbourhood`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-pricing-info-by-neighborhood.png)

6. Use the interactive visualisation to answer the following question:

    * For the Anza Vista neighbourhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012?

#### Build an Interactive Neighbourhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualisations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighbourhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighbourhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighbourhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighbourhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighbourhood_info_df` that groups the data by neighbourhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighbourhood_locations_df` DataFrame with the `all_neighbourhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighbourhoods_df`. The second cell cleans the data and sets the “Neighbourhood” column. Be sure to run these cells to create the `all_neighbourhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighbourhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `frame_width` parameter to 700.

    * Set the `frame_height` parameter to 500.

    * Include a descriptive title.

    Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighbourhood has the highest gross rent, and which has the highest sale price per square foot?

#### Compose Your Data Story

Based on the visualisations that you created, answer the following questions:

* How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighbourhoods across San Francisco?

* What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighbourhoods exist that you would suggest for investment, and why?

In [173]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path
import shapefile as shp
import matplotlib.pyplot as plt
import seaborn as sns

## Import the data 

In [174]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighbourhoods_census_data.csv file from the Resources folder
sfo_loco = Path(r"C:\Users\Weesam\Documents\School\UOFT Work\Challenge 6\Starter_Code\Resources\sfo_neighbourhoods_census_data.csv") # Location of my SFO data
sfo_data=pd.read_csv(sfo_loco) #Reads the CSV into a data frame
# Review the first five rows of the DataFrame
sfo_data.head(6) # Display the first five rows

year     neighbourhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239
5  2010    Central Sunset           418.172493         372560        1239

In [175]:
# Review the last five rows of the DataFrame
sfo_data.tail(6) #displays the last five rows

year           neighbourhood  sale_price_sqr_foot  housing_units  \
391  2016               Sunnyside           751.173709         384242   
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
391        4390  
392        4390  
393        4390  
394        4390  
395        4390  
396        4390

---

## Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualisation.

4. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting bar chart.](Images/6-4-zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analysing?

### Step 1: Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

In [176]:
housing_units_by_year = sfo_data.groupby('year').mean() # aggregation that groups the data by the year and then averages the results.
housing_units_by_year # Review the DataFrame

C:\Users\Weesam\AppData\Local\Temp\ipykernel_25204\1758689262.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  housing_units_by_year = sfo_data.groupby('year').mean() # aggregation that groups the data by the year and then averages the results.


sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

### Step 2: Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

### Step 3: Style and format the line plot to ensure a professionally styled visualisation.

In [177]:
# Create a visual aggregation explore the housing units by year
housing_units_by_year.hvplot.bar( x="year",  # x-axis represents the year column
    y="housing_units",  # y-axis represents the housing_units column
    title='Housing Units by Year',  # Set the plot title
    xlabel='Year',  # Label for the x-axis
    ylabel='Housing Units',  # Label for the y-axis
    width=800,  # Set the width of the plot
    height=400,  # Set the height of the plot
    color='#1f77b4',  # Set the color of the bars 
    legend=False,  # Disable the legend
    yformatter="%.0f",  # Format y-axis labels as integers
    ylim=(min(housing_units_by_year['housing_units']) - 1000, max(housing_units_by_year['housing_units']) + 1000) #Set y-axis limits with some buffer
)

:Bars   [year]   (housing_units)

### Step 5: Answer the following question:

**Question:** What is the overall trend in housing_units over the period being analysed?

**Answer:**  The number of housing units in the region increased steadily from 372,560 in 2010 to 384,242 in 2016, a upward trend. Simultaneously, the sale price per square foot rose from 369.34 in 2010 to 697.64 in 2016, and gross rent increased from 1239 in 2010 to 4390 in 2016. The significant increases in housing prices and rental costs reflect a surge in demand, proving a growing real estate market during this period.

---

## Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?

### Step 1: Group the data by year, and then average the results.

In [178]:
prices_square_foot_by_year = sfo_data.groupby('year').mean() # Create a numerical aggregation by grouping the data by year and averaging the results
prices_square_foot_by_year # Review the resulting DataFrame

C:\Users\Weesam\AppData\Local\Temp\ipykernel_25204\3795348394.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  prices_square_foot_by_year = sfo_data.groupby('year').mean() # Create a numerical aggregation by grouping the data by year and averaging the results


sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

**Question:** What is the lowest gross rent reported for the years included in the DataFrame?

**Answer:** The lowest gross rent reported for the years is 2010

### Step 2: Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

In [179]:
# Filter out the housing_units column, creating a new DataFrame 
sfo_data2=sfo_data.drop('housing_units',axis=1) # Keep only sale_price_sqr_foot and gross_rent averages per year
prices_square_foot_by_year = sfo_data2.groupby('year').mean() # the averages per year for only the sale price per square foot and the gross rent.
# Review the DataFrame
prices_square_foot_by_year

C:\Users\Weesam\AppData\Local\Temp\ipykernel_25204\3807565008.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  prices_square_foot_by_year = sfo_data2.groupby('year').mean() # the averages per year for only the sale price per square foot and the gross rent.


sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

### Step 3: Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

> **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`

### Step 4: Style and format the line plot to ensure a professionally styled visualisation.


In [180]:
# Plot prices_square_foot_by_year. 
# Inclued labels for the x- and y-axes, and a title.
housing_units_by_year.hvplot.line(  
    x='year',  # X-axis data is year
    y=['sale_price_sqr_foot', 'gross_rent'],  # Two lines for sale price per square foot and gross rent
    xlabel='Year',  # X-axis label
    ylabel='Price per Square Foot / Gross Rent',  # Y-axis label
    title='Sale Price per Square Foot and Gross Rent by Year',  # Plot title
    legend='top_left',  # Legend position
    width=800,  # Plot width
    height=400  # Plot height
)

:NdOverlay   [Variable]
   :Curve   [year]   (value)

### Step 6: Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

**Question:** Did any year experience a drop in the average sale price per square foot compared to the previous year?

**Answer:** Yes. Year 2010 avg sqft was 369, in 2011 sqft dropped to 341 then later in 2012 climbed to 399.

**Question:** If so, did the gross rent increase or decrease during that year?

**Answer:** Yes the rent did increase every year regardless of sqft increase or decrease. 

---

## Compare the Average Sale Prices by Neighbourhood

For this part of the assignment, use interactive visualisations and widgets to explore the average sale price per square foot by neighbourhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighbourhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighbourhood`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of the resulting plot.](Images/6-4-pricing-info-by-neighborhood.png)

6. Use the interactive visualisation to answer the following question:

    * For the Anza Vista neighbourhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012?


### Step 1: Create a new DataFrame that groups the original DataFrame by year and neighbourhood. Aggregate the results by the `mean` of the groups.

In [181]:
# Group by year and neighbourhood and then create a new dataframe of the mean values
prices_by_year_by_neighbourhood = sfo_data.groupby(['year','neighbourhood']).mean('sale_price_sqr_foot','gross_rent')

# Review the DataFrame
prices_by_year_by_neighbourhood.head()

sale_price_sqr_foot  housing_units  gross_rent
year neighbourhood                                                   
2010 Alamo Square               291.182945       372560.0      1239.0
     Anza Vista                 267.932583       372560.0      1239.0
     Bayview                    170.098665       372560.0      1239.0
     Buena Vista Park           347.394919       372560.0      1239.0
     Central Richmond           319.027623       372560.0      1239.0

### Step 2: Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [182]:
# Filter out the housing_units
prices_by_year_by_neighbourhood2 = prices_by_year_by_neighbourhood.drop('housing_units',axis=1)

# Review the first five rows of the DataFrame
prices_by_year_by_neighbourhood2.head()

sale_price_sqr_foot  gross_rent
year neighbourhood                                    
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

In [183]:
# Review the last five rows of the DataFrame
prices_by_year_by_neighbourhood2.tail()

sale_price_sqr_foot  gross_rent
year neighbourhood                                          
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

### Step 3: Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighbourhood`.

### Step 4: Style and format the line plot to ensure a professionally styled visualisation.

In [184]:
# Use hvplot to create an interactive line plot of the average price per square foot
prices_by_year_by_neighbourhood2.hvplot.line(
    x='year',  # X-axis data is year
    y=['sale_price_sqr_foot', 'gross_rent'],  # Two lines for sale price per square foot and gross rent
    xlabel='Year',  # X-axis label
    ylabel='Gross rent \ Sale Price Per Square Foot',  # Y-axis label
    title='Sale Price per Square Foot and Average Gross Rent -2010-2016 by Neighbourhood',  # Plot title
    legend='top_left', # Legend position
    groupby='neighbourhood',  # Grouping data by neighbourhood
   widget_location='top_right',  # Adding a dropdown selector for neighbourhood
)
# The plot should have a dropdown selector for the neighbourhood


Column
    [0] WidgetBox(align=('end', 'start'))
        [0] Select(margin=(20, 20, 20, 20), name='neighbourhood', options=['Alamo Square', ...], value='Alamo Square', width=250)
    [1] HoloViews(DynamicMap, height=300, sizing_mode='fixed', widget_location='top_right', width=700)

### Step 6: Use the interactive visualisation to answer the following question:

**Question:** For the Anza Vista neighbourhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

**Answer:** The average sale price per square foot for 2016 in the Anza Vista neighborhood is 88.402. This represents a decrease of 256.50 compared to the 2012 sale price per square foot, which was 344.491.

---

## Build an Interactive Neighbourhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualisations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighbourhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighbourhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighbourhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighbourhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighbourhood_info_df` that groups the data by neighbourhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighbourhood_locations_df` DataFrame with the `all_neighbourhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighbourhoods_df`. The second cell cleans the data and sets the “Neighbourhood” column. Be sure to run these cells to create the `all_neighbourhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighbourhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `frame_width` parameter to 700.

    * Set the `frame_height` parameter to 500.

    * Include a descriptive title.

    Note that your resulting plot should appear similar to the following image:

    ![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighbourhood has the highest gross rent, and which has the highest sale price per square foot?

### Step 1: Read the `neighbourhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighbourhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighbourhood”.

In [198]:
# Load neighbourhoods coordinates data
neighbourhood_locations_loco = Path(r"C:\Users\Weesam\Documents\School\UOFT Work\Challenge 6\Starter_Code\Resources\neighbourhoods_coordinates.csv") # Location of my neighbourhood data
neighbourhood_locations_data=pd.read_csv(neighbourhood_locations_loco) # Converts my CSV into a dataframe
# Display the DataFrame
neighbourhood_locations_data.head()

Neighbourhood        Lat         Lon
0     Alamo Square  37.791012 -122.402100
1       Anza Vista  37.779598 -122.443451
2          Bayview  37.734670 -122.401060
3  Bayview Heights  37.728740 -122.410980
4   Bernal Heights  37.728630 -122.443050

### Step 2: Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighbourhood_info_df` that groups the data by neighbourhood. Aggregate the results by the `mean` of the group.

In [186]:
# Calculate the mean values for each neighbourhood
all_neighbourhood_info = sfo_data.groupby('neighbourhood').mean()

# Review the resulting DataFrame
all_neighbourhood_info

year  sale_price_sqr_foot  housing_units  \
neighbourhood                                                         
Alamo Square        2013.000000           366.020712      378401.00   
Anza Vista          2013.333333           373.382198      379050.00   
Bayview             2012.000000           204.588623      376454.00   
Bayview Heights     2015.000000           590.792839      382295.00   
Bernal Heights      2013.500000           576.746488      379374.50   
...                         ...                  ...            ...   
West Portal         2012.250000           498.488485      376940.75   
Western Addition    2012.500000           307.562201      377427.50   
Westwood Highlands  2012.000000           533.703935      376454.00   
Westwood Park       2015.000000           687.087575      382295.00   
Yerba Buena         2012.500000           576.709848      377427.50   

                     gross_rent  
neighbourhood                    
Alamo Square        2817.285714  
Anza Vista          3031.833333  
Bayview             2318.400000  
Bayview Heights     3739.000000  
Bernal Heights      3080.333333  
...                         ...  
West Portal         2515.500000  
Western Addition    2555.166667  
Westwood Highlands  2250.500000  
Westwood Park       3959.000000  
Yerba Buena         2555.166667  

[73 rows x 4 columns]

### Step 3: Review the two code cells that concatenate the `neighbourhood_locations_df` DataFrame with the `all_neighbourhood_info_df` DataFrame. 

Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighbourhoods_df`. 

The second cell cleans the data and sets the “Neighbourhood” column. 

Be sure to run these cells to create the `all_neighbourhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

In [199]:
# Concatenate the dataframes
neighbourhood_locations_data.reset_index(drop=True, inplace=True) #Reset the Index for all_neighbourhood_info
all_neighbourhood_info.reset_index(drop=True, inplace=True) # #Reset the Index for all_neighbourhood_data
all_neighbourhoods_data = pd.concat([neighbourhood_locations_data,all_neighbourhood_info], axis=1) # Concat the two data frames
# Review the resulting DataFrame
all_neighbourhoods_data.head()


Neighbourhood        Lat         Lon         year  sale_price_sqr_foot  \
0     Alamo Square  37.791012 -122.402100  2013.000000           366.020712   
1       Anza Vista  37.779598 -122.443451  2013.333333           373.382198   
2          Bayview  37.734670 -122.401060  2012.000000           204.588623   
3  Bayview Heights  37.728740 -122.410980  2015.000000           590.792839   
4   Bernal Heights  37.728630 -122.443050  2013.500000           576.746488   

   housing_units   gross_rent  
0       378401.0  2817.285714  
1       379050.0  3031.833333  
2       376454.0  2318.400000  
3       382295.0  3739.000000  
4       379374.5  3080.333333

### Step 4: Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighbourhoods_df` DataFrame. Be sure to do the following:

* Set the `geo` parameter to True.
* Set the `size` parameter to “sale_price_sqr_foot”.
* Set the `color` parameter to “gross_rent”.
* Set the `frame_width` parameter to 700.
* Set the `frame_height` parameter to 500.
* Include a descriptive title.

In [200]:
# Create a plot to analyse neighbourhood info
geo_plot=all_neighbourhoods_data.hvplot.points(
    geo=True,  # Set the geo parameter to True for geographical plot
    x='Lon',  # X-axis data (longitude)
    y='Lat',   # Y-axis data (latitude)
    size='sale_price_sqr_foot',  # Size of points based on sale_price_sqr_foot
    color='gross_rent',  # Color of points based on gross_rent
    frame_width=700,  # Width of the frame
    frame_height=500,  # Height of the frame
    title='Neighborhood Information',  # Descriptive title for the plot
    tiles="OSM", # Get Satellite Image
)
geo_plot

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot)

### Step 5: Use the interactive map to answer the following question:

**Question:** Which neighbourhood has the highest gross rent, and which has the highest sale price per square foot?

**Answer:** WestWood Park has the highest gross rent and the highest sale price per square foot. 

## Compose Your Data Story

Based on the visualisations that you created, answer the following questions:

**Question:**  How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighbourhoods across San Francisco?

**Answer:** There is an upward trend in both sales prices and rental incomes across the various neighborhoods in San Francisco. Neighborhoods with higher average home prices and square footage, such as Westwood Park and Inner Parkside, are keen to higher prices, suggesting an overall increase in property values. 

**Question:** What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighbourhoods exist that you would suggest for investment, and why?

**Answer:** I think my company's potential about the one click is strategy that they are pursuing is a good one. Neighborhoods like Westwood Park and Inner Parkside have high average home prices, indicating they are potentially sought-after areas. These areas could yield substantial rental incomes due to their desirability. Investing in properties in these neighborhoods could result in excellent rental incomes, especially in areas like Westwood Park and Inner Parkside, which have high property values. Neighborhoods undergoing development like Mission Bay, could offer potential for future growth. 